import React from 'react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import MonthlyClose from './MonthlyClose';
import { monthlyCloseApi } from '../api/monthlyCloseApi';
import { reconciliationApi } from '../api/reconciliationApi';
import { AuthProvider, useAuth } from '../context/AuthContext';
import { PeriodProvider } from '../context/PeriodContext';

vi.mock('../api/reconciliationApi', () => ({
  reconciliationApi: {
    getReconciliationRecords: vi.fn(),
    getMonthEndReportPackage: vi.fn(),
    autoReconcilePeriod: vi.fn()
  }
}));

vi.mock('../api/gasFetch', () => ({
  gasFetch: vi.fn((action) => {
    if (action === 'getMonthlyCloseReadiness') {
      return Promise.resolve({
        success: true,
        periodKey: '2026-09',
        currentStatus: 'Open',
        readyToClose: true,
        reportPackagePrepared: false,
        blockingIssues: [],
        warnings: [],
        informational: [],
        financialSummary: { totalIncome: 10, totalRecognizedExpenses: 0, netPosition: 10, auditHealthScore: 100, scoreTier: 'Audit Ready', differenceAmount: 0 },
        counts: { transactionsCount: 1, reconciledTransactionsCount: 1, unreconciledTransactionsCount: 0, openCriticalIssues: 0, openHighIssues: 0 }
      });
    }
    if (action === 'getMonthlyCloseHistory') {
      return Promise.resolve({ success: true, history: [] });
    }
    if (action === 'getMonthlyClose') {
      return Promise.resolve({ success: true, closeRecord: null });
    }
    return Promise.resolve({ success: true });
  }),
  setActiveIdToken: vi.fn(),
  setOnUnauthorizedCallback: vi.fn()
}));

const TestWrapper = ({ children }) => {
  return (
    <AuthProvider>
      <PeriodProvider>
        <AuthInitializer>{children}</AuthInitializer>
      </PeriodProvider>
    </AuthProvider>
  );
};

const AuthInitializer = ({ children }) => {
  const { devSignIn } = useAuth();
  React.useEffect(() => {
    devSignIn('Primary Admin');
  }, [devSignIn]);
  return <>{children}</>;
};

describe('Monthly Close UI & Pre-Close Report Package Wording Suite', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it('renders PRE-CLOSE PREVIEW badge, Print Preview button, and open preview footer wording for OPEN period (A, C, D, E)', async () => {
    reconciliationApi.getMonthEndReportPackage.mockResolvedValue({
      success: true,
      periodKey: '2026-09',
      periodStart: '2026-09-01',
      periodEnd: '2026-09-30',
      generatedAt: '2026-09-04T08:00:00.000Z',
      churchInfo: { name: 'Grace and Praise Bangladeshi Church', ein: '39-4558295', address: 'San Bernardino' },
      closeStatus: 'Open',
      closedBy: 'N/A',
      closedAt: '',
      financialSummary: { totalIncome: 10, totalRecognizedExpenses: 0, netPosition: 10, sundayOfferingTotal: 10, auditHealthScore: 100 },
      sundayOfferingSummary: { totalSundayOffering: 10, count: 1, offerings: [] },
      reimbursementSummary: { count: 0, reimbursements: [] },
      checkSummary: { count: 0, checks: [] },
      capitalProjectSummary: { projects: [] },
      reconciliationSummary: { totalRecords: 1, reconciledCount: 1, matchedCount: 0, unmatchedCount: 0, differenceAmount: 0, differenceFormatted: '$0.00' },
      postCloseAdditionsCount: 0,
      postCloseDocuments: [],
      auditFindingsCount: 0,
      auditFindings: []
    });

    render(
      <TestWrapper>
        <MonthlyClose />
      </TestWrapper>
    );

    await waitFor(() => {
      expect(screen.getByText('Monthly Close & Close Readiness')).toBeInTheDocument();
    });

    // Click Report Package button
    const reportPkgBtn = screen.getByRole('button', { name: /report package/i });
    fireEvent.click(reportPkgBtn);

    await waitFor(() => {
      expect(screen.getByText(/DRAFT \/ PRE-CLOSE PREVIEW/i)).toBeInTheDocument();
    });

    // Check Print Preview button
    expect(screen.getByRole('button', { name: /print preview/i })).toBeInTheDocument();

    // Check Open-period wording present
    const openWording = screen.getAllByText((content, el) => el?.textContent?.includes('Pre-close preview generated by GPBC Finance Desk'));
    expect(openWording.length).toBeGreaterThan(0);

    // Check FALSE certification wording NOT present
    const falseWording = screen.queryAllByText((content, el) => el?.textContent?.includes('All records frozen under authoritative period lock rules'));
    expect(falseWording.length).toBe(0);

    // Check financial values unchanged
    expect(screen.getAllByText('$10.00').length).toBeGreaterThan(0);
  });

  it('renders FINAL / CLOSED badge, Print Report button, and closed certification wording for CLOSED period (B, E)', async () => {
    reconciliationApi.getMonthEndReportPackage.mockResolvedValue({
      success: true,
      periodKey: '2026-09',
      periodStart: '2026-09-01',
      periodEnd: '2026-09-30',
      generatedAt: '2026-09-04T08:00:00.000Z',
      churchInfo: { name: 'Grace and Praise Bangladeshi Church', ein: '39-4558295', address: 'San Bernardino' },
      closeStatus: 'Closed',
      closedBy: 'Primary Admin',
      closedAt: '2026-09-04T08:00:00.000Z',
      financialSummary: { totalIncome: 10, totalRecognizedExpenses: 0, netPosition: 10, sundayOfferingTotal: 10, auditHealthScore: 100 },
      sundayOfferingSummary: { totalSundayOffering: 10, count: 1, offerings: [] },
      reimbursementSummary: { count: 0, reimbursements: [] },
      checkSummary: { count: 0, checks: [] },
      capitalProjectSummary: { projects: [] },
      reconciliationSummary: { totalRecords: 1, reconciledCount: 1, matchedCount: 0, unmatchedCount: 0, differenceAmount: 0, differenceFormatted: '$0.00' },
      postCloseAdditionsCount: 0,
      postCloseDocuments: [],
      auditFindingsCount: 0,
      auditFindings: []
    });

    render(
      <TestWrapper>
        <MonthlyClose />
      </TestWrapper>
    );

    await waitFor(() => {
      expect(screen.getByText('Monthly Close & Close Readiness')).toBeInTheDocument();
    });

    const reportPkgBtn = screen.getByRole('button', { name: /report package/i });
    fireEvent.click(reportPkgBtn);

    await waitFor(() => {
      expect(screen.getByText(/FINAL \/ CLOSED/i)).toBeInTheDocument();
    });

    expect(screen.getByRole('button', { name: /print report/i })).toBeInTheDocument();
    const closedWording = screen.getAllByText((content, el) => el?.textContent?.includes('Certified by GPBC Finance Desk. Period 2026-09 is closed'));
    expect(closedWording.length).toBeGreaterThan(0);
    const actorWording = screen.getAllByText((content, el) => el?.textContent?.includes('Closed by Primary Admin'));
    expect(actorWording.length).toBeGreaterThan(0);
  });

  describe('Safe Close Confirmation Modal Suite (Section 13)', () => {
    it('opens confirmation modal on clicking Close Month without calling backend (A)', async () => {
      const closeMonthlyPeriodMock = vi.fn();
      monthlyCloseApi.closeMonthlyPeriod = closeMonthlyPeriodMock;

      render(
        <TestWrapper>
          <MonthlyClose />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByText('Monthly Close & Close Readiness')).toBeInTheDocument();
      });

      const closeMonthBtn = screen.getByRole('button', { name: /^close month$/i });
      fireEvent.click(closeMonthBtn);

      await waitFor(() => {
        expect(screen.getByText(/CLOSE PERIOD 2026-09/i)).toBeInTheDocument();
      });

      expect(closeMonthlyPeriodMock).not.toHaveBeenCalled();
    });

    it('safely closes modal without backend mutation when Cancel is clicked (B)', async () => {
      const closeMonthlyPeriodMock = vi.fn();
      monthlyCloseApi.closeMonthlyPeriod = closeMonthlyPeriodMock;

      render(
        <TestWrapper>
          <MonthlyClose />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByText('Monthly Close & Close Readiness')).toBeInTheDocument();
      });

      fireEvent.click(screen.getByRole('button', { name: /^close month$/i }));

      await waitFor(() => {
        expect(screen.getByText(/CLOSE PERIOD 2026-09/i)).toBeInTheDocument();
      });

      const cancelBtn = screen.getByRole('button', { name: /cancel/i });
      fireEvent.click(cancelBtn);

      await waitFor(() => {
        expect(screen.queryByText(/CLOSE PERIOD 2026-09/i)).not.toBeInTheDocument();
      });

      expect(closeMonthlyPeriodMock).not.toHaveBeenCalled();
    });

    it('keeps Confirm Close disabled until checkbox is checked AND typed text matches CLOSE 2026-09 (C, D)', async () => {
      render(
        <TestWrapper>
          <MonthlyClose />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByText('Monthly Close & Close Readiness')).toBeInTheDocument();
      });

      fireEvent.click(screen.getByRole('button', { name: /^close month$/i }));

      await waitFor(() => {
        expect(screen.getByText(/CLOSE PERIOD 2026-09/i)).toBeInTheDocument();
      });

      const confirmBtn = screen.getByRole('button', { name: /^confirm close$/i });
      expect(confirmBtn).toBeDisabled();

      // Check checkbox only
      const checkbox = screen.getByRole('checkbox');
      fireEvent.click(checkbox);
      expect(confirmBtn).toBeDisabled();

      // Type wrong confirmation
      const input = screen.getByPlaceholderText('CLOSE 2026-09');
      fireEvent.change(input, { target: { value: 'CLOSE 2026-08' } });
      expect(confirmBtn).toBeDisabled();

      // Type correct confirmation
      fireEvent.change(input, { target: { value: 'CLOSE 2026-09' } });
      expect(confirmBtn).not.toBeDisabled();
    });

    it('calls closeMonthlyPeriod once when modal confirmation is submitted (E, F)', async () => {
      const closeMonthlyPeriodMock = vi.fn().mockResolvedValue({ success: true, closeId: 'CLS-202609-123' });
      monthlyCloseApi.closeMonthlyPeriod = closeMonthlyPeriodMock;

      render(
        <TestWrapper>
          <MonthlyClose />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getByText('Monthly Close & Close Readiness')).toBeInTheDocument();
      });

      fireEvent.click(screen.getByRole('button', { name: /^close month$/i }));

      await waitFor(() => {
        expect(screen.getByText(/CLOSE PERIOD 2026-09/i)).toBeInTheDocument();
      });

      const checkbox = screen.getByRole('checkbox');
      fireEvent.click(checkbox);

      const input = screen.getByPlaceholderText('CLOSE 2026-09');
      fireEvent.change(input, { target: { value: 'CLOSE 2026-09' } });

      const confirmBtn = screen.getByRole('button', { name: /^confirm close$/i });
      fireEvent.click(confirmBtn);

      await waitFor(() => {
        expect(closeMonthlyPeriodMock).toHaveBeenCalledTimes(1);
        expect(closeMonthlyPeriodMock).toHaveBeenCalledWith(
          expect.objectContaining({
            periodKey: '2026-09'
          })
        );
      });
    });
  });

  describe('Authoritative Closed Period UI Suite (Section 2, 3, 4)', () => {
    it('renders PERIOD CLOSED & LOCKED banner, hides Close Month button, displays closedBy/closedAt, and renders history row', async () => {
      const { gasFetch } = await import('../api/gasFetch');
      vi.mocked(gasFetch).mockImplementation((action) => {
        if (action === 'getMonthlyCloseReadiness') {
          return Promise.resolve({
            success: true,
            periodKey: '2026-09',
            currentStatus: 'Closed',
            closedBy: 'gilbert.baidya@gmail.com',
            closedAt: '2026-09-04T15:47:24.831Z',
            readyToClose: false,
            reportPackagePrepared: true,
            blockingIssues: [],
            warnings: [],
            informational: [],
            financialSummary: { totalIncome: 10, totalRecognizedExpenses: 0, netPosition: 10, auditHealthScore: 100, scoreTier: 'Audit Ready', differenceAmount: 0 },
            counts: { transactionsCount: 1, reconciledTransactionsCount: 1, unreconciledTransactionsCount: 0, openCriticalIssues: 0, openHighIssues: 0 }
          });
        }
        if (action === 'getMonthlyCloseHistory') {
          return Promise.resolve({
            success: true,
            history: [
              {
                historyId: 'HIST-101',
                closeId: 'CLS-202609-907',
                periodKey: '2026-09',
                actionType: 'CLOSE',
                status: 'Closed',
                totalIncome: 10,
                totalRecognizedExpenses: 0,
                netPosition: 10,
                performedBy: 'gilbert.baidya@gmail.com',
                performedAt: '2026-09-04T15:47:24.831Z',
                notes: 'Regular monthly close'
              }
            ]
          });
        }
        return Promise.resolve({ success: true });
      });

      render(
        <TestWrapper>
          <MonthlyClose />
        </TestWrapper>
      );

      await waitFor(() => {
        expect(screen.getAllByText(/PERIOD CLOSED & LOCKED/i).length).toBeGreaterThan(0);
      });

      expect(screen.queryByRole('button', { name: /^close month$/i })).not.toBeInTheDocument();
      expect(screen.getAllByText(/gilbert.baidya@gmail.com/i).length).toBeGreaterThan(0);
      expect(screen.getByText('CLOSE')).toBeInTheDocument();
      expect(screen.getByText('✓ Closing Report Archived')).toBeInTheDocument();
    });
  });
});
