/*************************************************
 * GPBC Finance Desk — PresbyterReports.jsx
 * Executive Presbyter Financial Oversight Reporting Center
 *************************************************/

import React, { useState, useEffect } from 'react';
import {
  FileText,
  Printer,
  Mail,
  Download,
  Calendar,
  ShieldCheck,
  DollarSign,
  TrendingUp,
  RefreshCw,
  CheckCircle,
  AlertTriangle,
  Building,
  Layers,
  Lock
} from 'lucide-react';
import { reportApi } from '../api/reportApi';
import { useAuth } from '../context/AuthContext';

export default function PresbyterReports() {
  const { user } = useAuth();
  const isAdminOrEditor = user?.role === 'Primary Admin' || user?.role === 'Backup Admin' || user?.role === 'Finance Editor';

  const [periodKey, setPeriodKey] = useState(() => {
    const now = new Date();
    const y = now.getFullYear();
    const m = String(now.getMonth() + 1).padStart(2, '0');
    return `${y}-${m}`;
  });

  const [detailLevel, setDetailLevel] = useState('Summary');
  const [includeAuditAppendix, setIncludeAuditAppendix] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [successMessage, setSuccessMessage] = useState('');
  const [reportData, setReportData] = useState(null);
  const [reportList, setReportList] = useState([]);
  const [emailModalOpen, setEmailModalOpen] = useState(false);
  const [recipientEmail, setRecipientEmail] = useState('');
  const [emailLoading, setEmailLoading] = useState(false);
  const [currentReportId, setCurrentReportId] = useState('');

  const loadReportsList = React.useCallback(async () => {
    try {
      const res = await reportApi.getPresbyterReports();
      setReportList(res.reports || []);
    } catch (err) {
      console.error('Failed to load reports archive', err);
    }
  }, []);

  const handleGenerateReport = React.useCallback(async () => {
    setLoading(true);
    setError(null);
    setSuccessMessage('');
    try {
      const res = await reportApi.generatePresbyterReport({
        periodKey: periodKey,
        detailLevel: detailLevel,
        includeAuditAppendix: includeAuditAppendix,
        notes: `Generated by ${user?.name || user?.email}`
      });
      setReportData(res.reportData);
      setCurrentReportId(res.reportId);
      setSuccessMessage('Presbyter report generated successfully.');
      await loadReportsList();
    } catch (err) {
      setError(err?.message || 'Failed to generate report');
    } finally {
      setLoading(false);
    }
  }, [periodKey, detailLevel, includeAuditAppendix, user, loadReportsList]);

  useEffect(() => {
    handleGenerateReport();
    loadReportsList();
  }, [handleGenerateReport, loadReportsList]);

  const handlePrint = () => {
    window.print();
  };

  const handleSendEmail = async (e) => {
    e.preventDefault();
    if (!currentReportId || !recipientEmail.trim()) return;
    setEmailLoading(true);
    setError(null);
    try {
      await reportApi.sendPresbyterReport({
        reportId: currentReportId,
        recipientEmail: recipientEmail.trim()
      });
      setSuccessMessage(`Report sent to ${recipientEmail.trim()} successfully.`);
      setEmailModalOpen(false);
      setRecipientEmail('');
      await loadReportsList();
    } catch (err) {
      setError(err?.message || 'Failed to send report email');
    } finally {
      setEmailLoading(false);
    }
  };

  return (
    <div className="page-container" style={{ padding: '2rem', maxWidth: '1200px', margin: '0 auto' }}>
      {/* Header & Controls (Hidden when printing) */}
      <div className="no-print" style={{ marginBottom: '1.5rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '1rem', marginBottom: '1rem' }}>
          <div>
            <h1 style={{ fontSize: '1.6rem', color: 'var(--slate-blue-dark)', margin: 0, fontWeight: 700 }}>
              Presbyter Financial Oversight Reports
            </h1>
            <p style={{ color: 'var(--warm-gray)', fontSize: '0.9rem', margin: '4px 0 0 0' }}>
              Executive oversight summaries, fund distributions, capital projects, and board-ready reporting.
            </p>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flexWrap: 'wrap' }}>
            <div style={{ display: 'flex', alignItems: 'center', background: '#FFFFFF', border: '1px solid var(--mist-blue-dark)', borderRadius: '8px', padding: '4px 10px' }}>
              <Calendar size={16} style={{ color: 'var(--slate-blue)', marginRight: '8px' }} />
              <input
                type="month"
                value={periodKey}
                onChange={(e) => e.target.value && setPeriodKey(e.target.value)}
                style={{ border: 'none', background: 'transparent', outline: 'none', fontWeight: 600, color: 'var(--slate-blue-dark)', fontSize: '0.9rem' }}
              />
            </div>

            <select
              value={detailLevel}
              onChange={(e) => setDetailLevel(e.target.value)}
              style={{ background: '#FFFFFF', border: '1px solid var(--mist-blue-dark)', borderRadius: '8px', padding: '6px 12px', fontSize: '0.85rem', fontWeight: 600, color: 'var(--slate-blue-dark)', outline: 'none' }}
            >
              <option value="Summary">Summary View</option>
              <option value="Detailed">Detailed Breakdown</option>
            </select>

            <label style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.85rem', color: 'var(--slate-blue-dark)', fontWeight: 500, cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={includeAuditAppendix}
                onChange={(e) => setIncludeAuditAppendix(e.target.checked)}
              />
              Audit Appendix
            </label>

            <button
              onClick={handleGenerateReport}
              className="btn btn-primary"
              disabled={loading}
              style={{ display: 'flex', alignItems: 'center', gap: '6px' }}
            >
              <RefreshCw size={15} className={loading ? 'spinning' : ''} />
              Generate
            </button>

            <button
              onClick={handlePrint}
              className="btn btn-secondary"
              disabled={!reportData}
              style={{ display: 'flex', alignItems: 'center', gap: '6px' }}
            >
              <Printer size={15} />
              Print / PDF
            </button>

            {isAdminOrEditor && (
              <button
                onClick={() => setEmailModalOpen(true)}
                className="btn btn-secondary"
                disabled={!currentReportId}
                style={{ display: 'flex', alignItems: 'center', gap: '6px' }}
              >
                <Mail size={15} />
                Email Report
              </button>
            )}
          </div>
        </div>

        {error && (
          <div style={{ background: '#FCE8E6', border: '1px solid #FAD2CF', color: '#C5221F', padding: '12px 16px', borderRadius: '8px', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '10px' }}>
            <AlertTriangle size={18} />
            <span>{error}</span>
          </div>
        )}

        {successMessage && (
          <div style={{ background: '#E6F4EA', border: '1px solid #CEEAD6', color: '#137333', padding: '12px 16px', borderRadius: '8px', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '10px' }}>
            <CheckCircle size={18} />
            <span>{successMessage}</span>
          </div>
        )}
      </div>

      {/* Printable Report Document */}
      {reportData ? (
        <div
          id="presbyter-report-document"
          style={{
            background: '#FFFFFF',
            border: '1px solid var(--mist-blue-dark)',
            borderRadius: '12px',
            padding: '3rem',
            boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05)',
            color: '#1E293B',
            fontFamily: 'Inter, system-ui, sans-serif'
          }}
        >
          {/* Header & Church Info */}
          <div style={{ borderBottom: '2px solid var(--gold)', paddingBottom: '1.5rem', marginBottom: '2rem', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '1rem' }}>
            <div>
              <h1 style={{ fontSize: '1.8rem', color: 'var(--slate-blue-dark)', margin: 0, fontWeight: 800 }}>
                {reportData.churchInfo.name}
              </h1>
              <div style={{ fontSize: '0.85rem', color: 'var(--warm-gray)', marginTop: '4px' }}>
                EIN: {reportData.churchInfo.ein} • {reportData.churchInfo.address}
              </div>
              <div style={{ fontSize: '0.85rem', color: 'var(--warm-gray)' }}>
                Pastor: {reportData.churchInfo.pastor} • {reportData.churchInfo.website}
              </div>
            </div>

            <div style={{ textAlign: 'right' }}>
              <div style={{ fontSize: '1.2rem', fontWeight: 700, color: 'var(--slate-blue-dark)' }}>
                FINANCIAL OVERSIGHT REPORT
              </div>
              <div style={{ fontSize: '1rem', fontWeight: 600, color: 'var(--gold-dark)', marginTop: '2px' }}>
                Period: {reportData.periodKey} ({reportData.startDate} to {reportData.endDate})
              </div>
              {reportData.closeInfo && (
                <div style={{ marginTop: '6px', fontSize: '0.8rem', fontWeight: 600, color: reportData.closeInfo.status === 'Closed' ? '#137333' : '#B06000' }}>
                  {reportData.closeInfo.status === 'Closed' ? `🔒 Closed by ${reportData.closeInfo.closedBy || 'Admin'}` : `🔓 Reopened: ${reportData.closeInfo.reopenReason || 'Correction'}`}
                </div>
              )}
            </div>
          </div>

          {/* Executive Financial Summary */}
          <div style={{ marginBottom: '2rem' }}>
            <h2 style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--slate-blue-dark)', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1px solid var(--mist-blue-dark)', paddingBottom: '6px', marginBottom: '1rem' }}>
              1. Executive Financial Summary
            </h2>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem' }}>
              <div style={{ background: 'var(--ivory)', padding: '1rem', borderRadius: '8px', border: '1px solid var(--mist-blue-dark)' }}>
                <div style={{ fontSize: '0.8rem', color: 'var(--warm-gray)', fontWeight: 600 }}>TOTAL INCOME</div>
                <div style={{ fontSize: '1.4rem', fontWeight: 800, color: 'var(--forest-green)', marginTop: '4px' }}>
                  ${reportData.executiveSummary.totalIncome.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                </div>
                <div style={{ fontSize: '0.75rem', color: 'var(--warm-gray-light)', marginTop: '2px' }}>Tithes, Offerings & Gifts</div>
              </div>

              <div style={{ background: 'var(--ivory)', padding: '1rem', borderRadius: '8px', border: '1px solid var(--mist-blue-dark)' }}>
                <div style={{ fontSize: '0.8rem', color: 'var(--warm-gray)', fontWeight: 600 }}>OPERATING EXPENSES</div>
                <div style={{ fontSize: '1.4rem', fontWeight: 800, color: '#D93025', marginTop: '4px' }}>
                  ${reportData.executiveSummary.totalRecognizedExpenses.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                </div>
                <div style={{ fontSize: '0.75rem', color: 'var(--warm-gray-light)', marginTop: '2px' }}>Operating disbursements</div>
              </div>

              <div style={{ background: 'var(--ivory)', padding: '1rem', borderRadius: '8px', border: '1px solid var(--mist-blue-dark)' }}>
                <div style={{ fontSize: '0.8rem', color: 'var(--warm-gray)', fontWeight: 600 }}>NET OPERATING POSITION</div>
                <div style={{ fontSize: '1.4rem', fontWeight: 800, color: reportData.executiveSummary.netPosition >= 0 ? 'var(--forest-green)' : '#D93025', marginTop: '4px' }}>
                  ${reportData.executiveSummary.netPosition.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                </div>
                <div style={{ fontSize: '0.75rem', color: 'var(--warm-gray-light)', marginTop: '2px' }}>Surplus / (Deficit)</div>
              </div>

              <div style={{ background: 'var(--ivory)', padding: '1rem', borderRadius: '8px', border: '1px solid var(--mist-blue-dark)' }}>
                <div style={{ fontSize: '0.8rem', color: 'var(--warm-gray)', fontWeight: 600 }}>AUDIT HEALTH SCORE</div>
                <div style={{ fontSize: '1.4rem', fontWeight: 800, color: 'var(--slate-blue-dark)', marginTop: '4px' }}>
                  {reportData.executiveSummary.auditHealthScore} <span style={{ fontSize: '0.85rem', fontWeight: 500, color: 'var(--warm-gray)' }}>/ 100</span>
                </div>
                <div style={{ fontSize: '0.75rem', color: 'var(--warm-gray-light)', marginTop: '2px' }}>{reportData.executiveSummary.scoreTier}</div>
              </div>
            </div>
          </div>

          {/* Income & Expense Breakdowns */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem', marginBottom: '2rem' }}>
            <div>
              <h2 style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--slate-blue-dark)', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1px solid var(--mist-blue-dark)', paddingBottom: '6px', marginBottom: '1rem' }}>
                2. Income by Category
              </h2>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
                <tbody>
                  {Object.entries(reportData.incomeBreakdown).length === 0 ? (
                    <tr><td style={{ padding: '8px', color: 'var(--warm-gray)' }}>No income entries in this period.</td></tr>
                  ) : (
                    Object.entries(reportData.incomeBreakdown).map(([cat, amt], idx) => (
                      <tr key={idx} style={{ borderBottom: '1px solid var(--mist-blue)' }}>
                        <td style={{ padding: '6px 0', fontWeight: 500 }}>{cat}</td>
                        <td style={{ padding: '6px 0', textAlign: 'right', fontWeight: 600 }}>
                          ${amt.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>

            <div>
              <h2 style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--slate-blue-dark)', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1px solid var(--mist-blue-dark)', paddingBottom: '6px', marginBottom: '1rem' }}>
                3. Operating Expenses by Category
              </h2>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
                <tbody>
                  {Object.entries(reportData.expenseBreakdown).length === 0 ? (
                    <tr><td style={{ padding: '8px', color: 'var(--warm-gray)' }}>No recognized operating expenses in this period.</td></tr>
                  ) : (
                    Object.entries(reportData.expenseBreakdown).map(([cat, amt], idx) => (
                      <tr key={idx} style={{ borderBottom: '1px solid var(--mist-blue)' }}>
                        <td style={{ padding: '6px 0', fontWeight: 500 }}>{cat}</td>
                        <td style={{ padding: '6px 0', textAlign: 'right', fontWeight: 600 }}>
                          ${amt.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>

          {/* Designated Funds & Capital Projects */}
          <div style={{ marginBottom: '2rem' }}>
            <h2 style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--slate-blue-dark)', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1px solid var(--mist-blue-dark)', paddingBottom: '6px', marginBottom: '1rem' }}>
              4. Designated Funds & Restricted Balances
            </h2>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid var(--mist-blue-dark)', textAlign: 'left', color: 'var(--warm-gray)' }}>
                  <th style={{ padding: '6px 0' }}>Fund Name</th>
                  <th style={{ padding: '6px 0', textAlign: 'right' }}>Total Received</th>
                  <th style={{ padding: '6px 0', textAlign: 'right' }}>Total Disbursed</th>
                  <th style={{ padding: '6px 0', textAlign: 'right' }}>Net Restricted Balance</th>
                </tr>
              </thead>
              <tbody>
                {reportData.designatedFunds.map((f, idx) => (
                  <tr key={idx} style={{ borderBottom: '1px solid var(--mist-blue)' }}>
                    <td style={{ padding: '6px 0', fontWeight: 600 }}>{f.fundId}</td>
                    <td style={{ padding: '6px 0', textAlign: 'right' }}>${f.totalIncome.toLocaleString('en-US', { minimumFractionDigits: 2 })}</td>
                    <td style={{ padding: '6px 0', textAlign: 'right' }}>${f.totalExpenses.toLocaleString('en-US', { minimumFractionDigits: 2 })}</td>
                    <td style={{ padding: '6px 0', textAlign: 'right', fontWeight: 700, color: f.netBalance >= 0 ? 'var(--forest-green)' : '#D93025' }}>
                      ${f.netBalance.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Capital Projects */}
          {reportData.capitalProjects.length > 0 && (
            <div style={{ marginBottom: '2rem' }}>
              <h2 style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--slate-blue-dark)', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1px solid var(--mist-blue-dark)', paddingBottom: '6px', marginBottom: '1rem' }}>
                5. Capital Projects Oversight
              </h2>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
                <thead>
                  <tr style={{ borderBottom: '1px solid var(--mist-blue-dark)', textAlign: 'left', color: 'var(--warm-gray)' }}>
                    <th style={{ padding: '6px 0' }}>Project</th>
                    <th style={{ padding: '6px 0' }}>Status</th>
                    <th style={{ padding: '6px 0', textAlign: 'right' }}>Budget</th>
                    <th style={{ padding: '6px 0', textAlign: 'right' }}>Donations</th>
                    <th style={{ padding: '6px 0', textAlign: 'right' }}>Paid</th>
                    <th style={{ padding: '6px 0', textAlign: 'right' }}>Remaining Balance</th>
                  </tr>
                </thead>
                <tbody>
                  {reportData.capitalProjects.map((p, idx) => (
                    <tr key={idx} style={{ borderBottom: '1px solid var(--mist-blue)' }}>
                      <td style={{ padding: '6px 0', fontWeight: 600 }}>{p.projectName}</td>
                      <td style={{ padding: '6px 0' }}>{p.status}</td>
                      <td style={{ padding: '6px 0', textAlign: 'right' }}>${p.approvedBudget.toLocaleString('en-US', { minimumFractionDigits: 2 })}</td>
                      <td style={{ padding: '6px 0', textAlign: 'right' }}>${p.designatedDonationsReceived.toLocaleString('en-US', { minimumFractionDigits: 2 })}</td>
                      <td style={{ padding: '6px 0', textAlign: 'right' }}>${p.expensesPaid.toLocaleString('en-US', { minimumFractionDigits: 2 })}</td>
                      <td style={{ padding: '6px 0', textAlign: 'right', fontWeight: 700, color: p.remainingDesignatedBalance >= 0 ? 'var(--forest-green)' : '#D93025' }}>
                        ${p.remainingDesignatedBalance.toLocaleString('en-US', { minimumFractionDigits: 2 })}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Reimbursements & Settlements Overview */}
          <div style={{ marginBottom: '2rem' }}>
            <h2 style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--slate-blue-dark)', textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1px solid var(--mist-blue-dark)', paddingBottom: '6px', marginBottom: '1rem' }}>
              6. Member Reimbursements & Liability Settlements
            </h2>
            <div style={{ fontSize: '0.85rem', color: 'var(--warm-gray)', lineHeight: 1.6 }}>
              Total Reimbursement Payouts in Period: <strong>${reportData.executiveSummary.settlementPayouts.toLocaleString('en-US', { minimumFractionDigits: 2 })}</strong> across <strong>{reportData.reimbursementsOverview.count}</strong> approved claim(s).
              Reimbursement cash settlements are strictly accounted as payable settlements and excluded from recognized operating expenses to prevent double-counting.
            </div>
          </div>

          {/* Audit Appendix (Optional) */}
          {reportData.auditAppendix && reportData.auditAppendix.length > 0 && (
            <div style={{ marginTop: '2rem', borderTop: '2px solid var(--slate-blue)', paddingTop: '1.5rem' }}>
              <h2 style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--slate-blue-dark)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '1rem' }}>
                Appendix: Audit & Compliance Findings ({reportData.auditAppendix.length})
              </h2>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8rem' }}>
                <thead>
                  <tr style={{ borderBottom: '1px solid var(--mist-blue-dark)', textAlign: 'left', color: 'var(--warm-gray)' }}>
                    <th style={{ padding: '6px 0' }}>Severity</th>
                    <th style={{ padding: '6px 0' }}>Rule</th>
                    <th style={{ padding: '6px 0' }}>Finding Description</th>
                    <th style={{ padding: '6px 0' }}>Status</th>
                    <th style={{ padding: '6px 0' }}>Recommended Action</th>
                  </tr>
                </thead>
                <tbody>
                  {reportData.auditAppendix.map((item, idx) => (
                    <tr key={idx} style={{ borderBottom: '1px solid var(--mist-blue)' }}>
                      <td style={{ padding: '6px 0', fontWeight: 700, color: item.severity === 'CRITICAL' ? '#D93025' : item.severity === 'HIGH' ? '#B06000' : 'var(--slate-blue)' }}>
                        {item.severity}
                      </td>
                      <td style={{ padding: '6px 0', fontFamily: 'monospace' }}>{item.ruleId}</td>
                      <td style={{ padding: '6px 0' }}>{item.description}</td>
                      <td style={{ padding: '6px 0' }}>{item.status}</td>
                      <td style={{ padding: '6px 0', color: 'var(--warm-gray)' }}>{item.recommendedAction}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Signatures & Oversight Statement */}
          <div style={{ marginTop: '3rem', borderTop: '1px solid var(--mist-blue-dark)', paddingTop: '1.5rem', display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', color: 'var(--warm-gray)' }}>
            <div>
              <div>Prepared for: Presbyter & Board Oversight</div>
              <div>Generated: {new Date(reportData.generatedAt).toLocaleString()}</div>
            </div>
            <div style={{ textAlign: 'right' }}>
              <div style={{ borderBottom: '1px solid #94A3B8', width: '220px', marginBottom: '4px' }}></div>
              <div>Authorized Signatory / Pastor</div>
            </div>
          </div>
        </div>
      ) : (
        <div style={{ textAlign: 'center', padding: '3rem', color: 'var(--warm-gray)' }}>
          Select a reporting period and click Generate to preview the Presbyter Financial Report.
        </div>
      )}

      {/* Generated Reports Archive (Hidden when printing) */}
      <div className="no-print" style={{ marginTop: '2rem' }}>
        <div className="glass-panel" style={{ padding: '1.5rem', borderRadius: '10px' }}>
          <h2 style={{ fontSize: '1.1rem', color: 'var(--slate-blue-dark)', fontWeight: 700, marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <FileText size={18} />
            Generated Reports Archive ({reportList.length})
          </h2>

          {reportList.length === 0 ? (
            <div style={{ textAlign: 'center', padding: '1.5rem', color: 'var(--warm-gray)', fontSize: '0.9rem' }}>
              No archived reports found. Reports generated here will be recorded in the master workbook.
            </div>
          ) : (
            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
                <thead>
                  <tr style={{ borderBottom: '1px solid var(--mist-blue-dark)', textAlign: 'left', color: 'var(--warm-gray)' }}>
                    <th style={{ padding: '8px' }}>Report ID</th>
                    <th style={{ padding: '8px' }}>Period</th>
                    <th style={{ padding: '8px' }}>Income</th>
                    <th style={{ padding: '8px' }}>Expenses</th>
                    <th style={{ padding: '8px' }}>Net Position</th>
                    <th style={{ padding: '8px' }}>Score</th>
                    <th style={{ padding: '8px' }}>Generated By</th>
                    <th style={{ padding: '8px' }}>Date</th>
                  </tr>
                </thead>
                <tbody>
                  {reportList.map((r, idx) => (
                    <tr key={idx} style={{ borderBottom: '1px solid var(--mist-blue)' }}>
                      <td style={{ padding: '8px', fontWeight: 600 }}>{r.reportId}</td>
                      <td style={{ padding: '8px' }}>{r.periodKey}</td>
                      <td style={{ padding: '8px' }}>${Number(r.totalIncome || 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}</td>
                      <td style={{ padding: '8px' }}>${Number(r.totalExpenses || 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}</td>
                      <td style={{ padding: '8px', fontWeight: 600, color: (r.netPosition || 0) >= 0 ? 'var(--forest-green)' : '#D93025' }}>
                        ${Number(r.netPosition || 0).toLocaleString('en-US', { minimumFractionDigits: 2 })}
                      </td>
                      <td style={{ padding: '8px' }}>{r.auditHealthScore}</td>
                      <td style={{ padding: '8px' }}>{r.generatedBy}</td>
                      <td style={{ padding: '8px', color: 'var(--warm-gray-light)' }}>{r.generatedAt ? new Date(r.generatedAt).toLocaleDateString() : ''}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>

      {/* Email Report Modal */}
      {emailModalOpen && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: '1rem' }}>
          <div style={{ background: '#FFFFFF', borderRadius: '12px', padding: '2rem', maxWidth: '480px', width: '100%', boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '1rem', color: 'var(--slate-blue-dark)' }}>
              <Mail size={22} />
              <h3 style={{ margin: 0, fontSize: '1.2rem', fontWeight: 700 }}>Send Report via Email</h3>
            </div>
            <p style={{ fontSize: '0.85rem', color: 'var(--warm-gray)', marginBottom: '1.25rem' }}>
              Send this Presbyter Financial Oversight Report to an authorized church leader or presbyter.
            </p>

            <form onSubmit={handleSendEmail}>
              <div style={{ marginBottom: '1.25rem' }}>
                <label style={{ display: 'block', fontSize: '0.85rem', fontWeight: 600, marginBottom: '6px', color: 'var(--slate-blue-dark)' }}>
                  Recipient Email *
                </label>
                <input
                  type="email"
                  required
                  value={recipientEmail}
                  onChange={(e) => setRecipientEmail(e.target.value)}
                  placeholder="e.g. presbyter@gracepraise.church"
                  style={{ width: '100%', padding: '8px 12px', borderRadius: '8px', border: '1px solid var(--mist-blue-dark)', fontSize: '0.85rem', outline: 'none' }}
                />
              </div>

              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px' }}>
                <button
                  type="button"
                  onClick={() => setEmailModalOpen(false)}
                  className="btn btn-secondary"
                  disabled={emailLoading}
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="btn btn-primary"
                  disabled={emailLoading || !recipientEmail.trim()}
                >
                  {emailLoading ? 'Sending...' : 'Send Email'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
